############# Romanian navigation ##############

# main menu


[[main]]
name = "Despre"
url = "despre-mine/"
weight = 2

[[main]]
name = "Corporate"
url = "servicii/psihologie-organizationala/"
weight = 4

[[main]]
weight = 3
name = "Servicii"
url = "servicii/"
hasChildren = true

  [[main]]
  parent = "Servicii"
  name = "Terapie Individuală"
  url = "servicii/terapie-individuala/"
  weight = 1

  [[main]]
  parent = "Servicii"
  name = "Terapie de Cuplu"
  url = "servicii/terapie-de-cuplu/"
  weight = 2

  [[main]]
  parent = "Servicii"
  name = "Terapie de Familie"
  url = "servicii/terapie-de-familie/"
  weight = 3





[[main]]
weight = 6
name = "Resurse"
url = "resurse/"
hasChildren = true

  [[main]]
  parent = "Resurse"
  name = "Articole"
  url = "resurse/articole/"
  weight = 1

  [[main]]
  parent = "Resurse"
  name = "Teste Psihologice"
  url = "resurse/teste-psihologice/"
  weight = 2

[[main]]
name = "Contact"
url = "contact/"
weight = 7


# footer menu
[[footer]]
name = "Despre"
url = "despre-mine/"
weight = 1

[[footer]]
name = "Abordare"
url = "abordare/"
weight = 2

[[footer]]
name = "Resurse"
url = "resurse/"
weight = 3

[[footer]]
name = "Contact"
url = "contact/"
weight = 4

[[footer]]
name = "Termeni & Condiții"
url = "termeni-si-conditii/"
weight = 5


