############# Romanian navigation ##############

# main menu

[[main]]
name = "Acasă"
url = "/"
weight = 1

[[main]]
name = "Despre"
url = "despre-mine/"
weight = 2

[[main]]
name = "Abordare"
url = "abordare/"
weight = 4

[[main]]
weight = 3
name = "Servicii"
url = "servicii/"
hasChildren = true

  [[main]]
  parent = "Servicii"
  name = "Terapie Individuală"
  url = "servicii/terapie-individuala/"
  weight = 1

  [[main]]
  parent = "Servicii"
  name = "Terapie de Cuplu"
  url = "servicii/terapie-de-cuplu/"
  weight = 2

  [[main]]
  parent = "Servicii"
  name = "Terapie de Familie"
  url = "servicii/terapie-de-familie/"
  weight = 3

  [[main]]
  parent = "Servicii"
  name = "Psihologie Organizațională"
  url = "servicii/psihologie-organizationala/"
  weight = 4





[[main]]
name = "Resurse"
url = "resurse/"
weight = 6

[[main]]
name = "Contact"
url = "contact/"
weight = 7


# footer menu
[[footer]]
name = "Despre"
url = "despre-mine/"
weight = 1

[[footer]]
name = "Servicii"
url = "servicii/"
weight = 2

[[footer]]
name = "Abordare"
url = "abordare/"
weight = 3

[[footer]]
name = "Resurse"
url = "resurse/"
weight = 4

[[footer]]
name = "Contact"
url = "contact/"
weight = 5

[[footer]]
name = "Termeni & Condiții"
url = "termeni-si-conditii/"
weight = 6


