############# English navigation ##############

# main menu

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
weight = 3
name = "Services"
url = "services/"
hasChildren = true

  [[main]]
  parent = "Services"
  name = "Individual Therapy"
  url = "services/individual-therapy/"
  weight = 1

  [[main]]
  parent = "Services"
  name = "Couples Therapy"
  url = "services/couples-therapy/"
  weight = 2

  [[main]]
  parent = "Services"
  name = "Family Therapy"
  url = "services/family-therapy/"
  weight = 3

[[main]]
name = "Corporate"
url = "services/organizational-psychology/"
weight = 4

[[main]]
weight = 6
name = "Resources"
url = "resources/"
hasChildren = true

  [[main]]
  parent = "Resources"
  name = "Articles"
  url = "resources/articles/"
  weight = 1

  [[main]]
  parent = "Resources"
  name = "Psychological Tests"
  url = "resources/psychological-tests/"
  weight = 2

[[main]]
name = "Contact"
url = "contact/"
weight = 7


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Approach"
url = "approach/"
weight = 2

[[footer]]
name = "Resources"
url = "resources/"
weight = 3

[[footer]]
name = "Contact"
url = "contact/"
weight = 4

[[footer]]
name = "Terms & Conditions"
url = "terms-and-conditions/"
weight = 5

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 6
