############# Romanian navigation ##############

# main menu


[[main]]
name = "Despre"
url = "about/"
weight = 2

[[main]]
name = "Corporate"
url = "corporate/"
weight = 5


[[main]]
weight = 3
name = "Psihoterapie"
hasChildren = true

  [[main]]
  parent = "Psihoterapie"
  name = "Psihoterapie Individuala"
  url = "terapie-individuala/"
  weight = 2
  [[main]]
  parent = "Psihoterapie"
  name = "Psihoterapie de Familie"
  url = "terapie-de-familie/"
  weight = 5
  [[main]]
  parent = "Psihoterapie"
  name = "Psihoterapie de Cuplu"
  url = "terapie-de-cuplu/"
  weight = 3

  [[main]]
  parent = "Psihoterapie"
  name = "Dezvoltare Personala"
  url = "dezvoltare-personala/"
  weight = 8





[[main]]
weight = 9
name = "Resurse"
hasChildren = true

  [[main]]
  parent = "Resurse"
  name = "Teste"
  url = "test/"
  weight = 2

  [[main]]
  parent = "Resurse"
  name = "Blog"
  url = "blog/"
  weight = 1

  [[main]]
  parent = "Resurse"
  name = "Articole"
  url = "articole/"
  weight = 5

  [[main]]
  parent = "Resurse"
  name = "Intrebari frecvente"
  url = "intrebari/"
  weight = 10


[[main]]
name = "Contact"
url = "contact/"
weight = 7


# footer menu
[[footer]]
name = "Despre"
url = "about/"
weight = 1

[[footer]]
name = "Servicii"
url = "servicii/"
weight = 2

[[footer]]
name = "Termeni & Conditii"
url = "terms-and-conditions/"
weight = 3


